### ISSUE TITLE
uhhhhhh

### ISSUE THREAD

**Issue by SpeckyYT** [ZangiTheDev/ITMS#1]
`1i` is for items (AKA counters), not for object IDs
also this list is already in spwn, if you do `$.print(obj_ids)` you'll get most of the useful ones

**Comment by itsmebombie** [comment]
true💀

**Comment by SpeckyYT** [comment]
plus, it's not a library

**Comment by ZangiTheDev** [comment]
ohh damn
ill take it down
my bad
